language: node_js
node_js:
- node
before_deploy: npm run package
deploy:
  provider: releases
  api_key:
    secure: "YPvQal6qIvYufWXTa0bCaiOZAdJ+KRzMO1Xakcr7k5qeEXNzZbbpNTtOWfo7aSJnqvosm9s53Rp0mtKPhghOXNp7e/VualysZ65a4P03zJ3CwGjToSf/B1vjjh05Zj/yIgdvK1FMdG5Ph1iiqX9Qul7oIymxMDcLEHY97VyemOYwGaWaQx/B6l0FgGaBLyiR6sRXOSf2Ir4bLESG723b+T4LTy0FLbdMvy3Vyujs42m8JlX09om34Y/Fs4mBUa+Pyo/5UuzX7CJJ8vyKpWNqcmm4vpr0g3AoRfAKmbQ0kNkiB9SORJMJq5cfmf291dotsUJZ0vyEMCVFjIGUS4TPUbPJnQ7VdwR1RU3OKQ+LQsO6pecvf4OB0U6y/KQmwCIp0PAuFV0n8wcUfAY72OFMtMbcxu2qf+h+KZ+a137tldaUJGDwA3UhcsqyMzoNFGWHavKmQVxVocaJwDIJiG7r5+mI6oA9h0YdicEPRcsbe6vZlDUJuMZktM7DL0LqXsbkZRsVneCi+brm2kemqhFTdZod9JGqzlHFG6dZWHtIrUmnmIr3QEQccsH7MJCi+/ALSo3khN9eNw2w7XArRaig8xNd2b6eBI9vnH+gyAjtGBPUQ6y8LfqVbgU6BBj97Kv488Q453rhTJNkP2/WcEagr30lTcbji10sXokW/PEcbQw="
  file: wukong-web.tgz
  on:
    repo: GyrosWorkshop/WukongWeb
    tags: true
