language: node_js
node_js:
- node
before_deploy: npm run package
deploy:
  provider: releases
  api_key:
    secure: "YPvQal6qIvYufWXTa0bCaiOZAdJ+KRzMO1Xakcr7k5qeEXNzZbbpNTtOWfo7aSJnqvosm9s53Rp0mtKPhghOXNp7e/VualysZ65a4P03zJ3CwGjToSf/B1vjjh05Zj/yIgdvK1FMdG5Ph1iiqX9Qul7oIymxMDcLEHY97VyemOYwGaWaQx/B6l0FgGaBLyiR6sRXOSf2Ir4bLESG723b+T4LTy0FLbdMvy3Vyujs42m8JlX09om34Y/Fs4mBUa+Pyo/5UuzX7CJJ8vyKpWNqcmm4vpr0g3AoRfAKmbQ0kNkiB9SORJMJq5cfmf291dotsUJZ0vyEMCVFjIGUS4TPUbPJnQ7VdwR1RU3OKQ+LQsO6pecvf4OB0U6y/KQmwCIp0PAuFV0n8wcUfAY72OFMtMbcxu2qf+h+KZ+a137tldaUJGDwA3UhcsqyMzoNFGWHavKmQVxVocaJwDIJiG7r5+mI6oA9h0YdicEPRcsbe6vZlDUJuMZktM7DL0LqXsbkZRsVneCi+brm2kemqhFTdZod9JGqzlHFG6dZWHtIrUmnmIr3QEQccsH7MJCi+/ALSo3khN9eNw2w7XArRaig8xNd2b6eBI9vnH+gyAjtGBPUQ6y8LfqVbgU6BBj97Kv488Q453rhTJNkP2/WcEagr30lTcbji10sXokW/PEcbQw="
  file: wukong-web.tgz
  on:
    repo: GyrosWorkshop/WukongWeb
    tags: true
env:
  global:
    secure: YVNWwBAx8icPTt+ZZKgmkdhN7gbP0W19XIUwImne0ab7M/Pkx2NOiDW4wO6efynVtHf64R/ue55Bsry3JRQpvp0f0y5dY3XBUNoyNWZ/WRbRkOmZr5l/uEYYsGX7ry3Ww2EYawVbh9QPDp/ufzZgff7Hm8f/qBfH02lRPpzS8WTIFDG0DNNrYVEJXoAPPEeD9/JBwqWopCBw4gAcOSfA14YwfSORY0VDD5jKN9XqHbekfZkfoQJcp/+K5kj2PWlrOWZfBy4EodjW+X7CfIX62xaMemMuRkduqqr6yBbnVw2kRWmnBao4vC//rLG4/kXOnZATFbfs3SWo/94NT5rC0Hn4XolUhI3mYdFs3uNy+0BRH+DLennIo0o+R9P0UWKpwaQAvyNaqyinH6IDV8NfE+SGUM00nMNtLdjqSYHDzFuYfMEzY4p5LL1Zc3ONKx5OXfXnljr6142FVT7D/1RBbbj0YtznRpBij+ky2GY+DyVByQ78deCyTAcNw8uMUUO7PxN01DleU2K/SeqX2FReDdjStmXb6FN4nlHtKa50jw0ad0cdZtrLKUo9qwVHRKPvVRZIgYW+PTFyNHQ10hu8gjNnww10Q2vdbpkq+UIKb41ujYz/L+t2PlQT3nDpi2Nr4v8JWcBo8gpOnlKKAv0xREkPOOfrp3/jyUojy+sk5ig=
