dist: trusty
sudo: false
language: node_js
node_js:
- node

before_script:
  - npm install -g travis-ci-cloudfront-invalidation

deploy:
  provider: s3
  on:
    repo: GyrosWorkshop/WukongWeb
    tags: true
  bucket: wukong-frontend
  region: ap-northeast-1
  local_dir: build
  detect_encoding: true
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAIHXJAIN2JAVUYVNA
  secret_access_key:
    secure: pWKGEouClvP2y67g0DJ8omZ9CP7zjjEQTMI3KM5UM8ZvrxmidGo1cr93yqTGQoYL0jiwSI0uULlCskR4MLQhwZ5dZTrske8c6jZYgqbh96l7KiiRS8EXCzloWLjxsBmENY7kpd2b9rxKBYsp1X+KJSTL2qJKki/gLR0tEziMbe6iDOpxYtxhf4/iYpc6djBdn13tpP4waDikAf5UJ+sQ4Wdvr2+d366z9TnyBFDfFGXa5a2eb4WF5cNJ8326OQCUWd7WTvcflGxv/S+Os88LI0hAnN95eWKfdxUWq2kj3E52qvPiR2QLjH6xk6qor6ZcoEQ8UbKJx/i089NYlodfCAkeRYCpGGJkUOy/t7hA7EXAllW0n0WST51SfkM+HhAhEdBdT/jB31dPW4INFuOfUmDuQPfCE7aqoQ6Xz0nwiKYU7qjFrUFdkUgrvmsKlgtPOgVXJlgYJvHGXuVc9ejKuWbBmj1ik2Rj+MR7dwVoA41djUavfKsyl3DXW6dU457aZ1VNr/h1TQ7ny7wo3cXMQ+HGWN5aFY9LOZikjYbx5pH84lJj6aXxqsAGGDwHf+QwEDlAUC7BHSMFL/HgVDya5eVZY+072vYxzkMtvkrrIVwRsaTbX+NGy3FhVbDgcw/CCXA6GiEsWDd6oQF/7mavsMqXZLcbkHuo7ITS/g1O+ck=

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWSAccessKey -s $AWSSecretKey -c $CloudFrontDistributionId -i '*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST

env:
  global:
  - secure: mtiPVYa0XeQDTWv7HOJ4zqM1ry6JxjDPkMSwn4vssRYen5rl3jRQMdmHtpP5Pcyj4pRISyazCPc274sfxfblhQptYSK1HpQaEBuDcDqCSXg7yPiOK3GOI4u33sBbXDn6NHEoNGGzl13+6V4gFcS0OBjUl3jPHT9q7BNafHZSSapCPwl1LdlE7YVsUVBV0Th5l6G5axXly3JXugXi+qsgui4pP3w6UQj/bS9QNCw3KgtHwG3+c+IhLlfB19exzVV7X8BUf1O9f0T/nVBZhfkkXp/exs0g4nk1kZRVBHFeVoCpDLzINGcTVqdSwWLQVZtqLxG6yRlif3OXR9lqbIL7D0egv8GpKWdAyoN/fiiTBzrMsHYN5A823UbUPeIX+nk1mIvzi9IuRCXAembeGWl0XBLCQC7USryGnldLA2SSAtgbV2ARCBo+uvPUfQfYoMs/nhzzNJRpnFKELEfgFG7Z3icPlUra0pFJtGxlNVoqxr4EWyfRHyDMWY/eHVp6AM+T1/fQDxmxB5npDXwy6gRoWtx4mq+xEggtm3nRCxGT0ln5jJObAxjy8js0ZVxdviwbOHj3eSQLC3fF6/Qz+tlFInA3axJcJDi9UQsD/fr+zqDE4BDt0Ukh9xLVoFiRhNgmROviXUhwTcyMHzfyG/kNG0YkZYc3iSZmq8TSVs3b91g=
  - secure: SH6UkeWKUsBCGsW4egXpP9GMNaIf+tOzHyPSnlFvE2BR596keov49dUZmYIC7mXkK8PLVU9rnjUN7Icx4QHQIrHoDmP27u72aFjRL4InhPRkE6aVlT0KgrN27kedxiG62yUb8NNi6aA2aj6AFoDOK3xa/muA0l9BPMU7czR/OO8ODJdfEPEsfKoyRn8qXy34sXvvHPoQTu6zCrBB+TrlJ44SLrhHgHYeXANUJHUUUB1GiDT/DoSo5Rowzu1Z3J/Lgzkos7nL8D2XKfF3hZieAwrxJRxorGAhYObFwfEWEa+J6dIvxaZbUp0w3cJtPnOINMWA25OQF0lTvVoYYO2IzlJxzjXES51qcD0iTTTVHMkqAlIEe0RUwy+mpwzENoqrSHEPfERvDvItUSDdAMdxX6CXTsrhEzGwTk9Z8/CloQw1nBBZRjcnaSdlAv9BG+biLVJyVZ9kWvW9XbPjiHbctLKcuejxkOoZ52HEb4ltTGNVQdWWOzsB/Iw6K2fFma4h/S2BMkbnMJwqDGo1bQcdYunhSGI41+yLlS/FDsWw6j20452sFZvzvOI0WDLevnXfkVw/i5obEZYnfjG6FbAcFAqpF+Tgt/f/SFNr07xEg7Uac+6Cgzx6eLye8promM7ShOpbpS9/FFevyyLTgOMtNi9cy4SoSG3Eeg5hY0COBNA=
  - secure: I4MgjxpqjI8uQEAxf//eBclwwwa2oe/aZKpB4cxrnCTva+wQsMNmvMvzSuUHKoDSbkNx6ck8As980Nnm25liq5R8U6hkEYtKo52IjmTsE1z77r8L03mJcHE3ck2zxA9fovjORwkgtWMJwyxa/1ShUJBAC75EOClQIOA1K3kWzyEx6zVnNjooWp2kNnATIPthF8g2zerSky/M/rrkSDyAzgZgpOI7QV/Lqmu5cNiGpngFpNF4NYEJfCOEBjjIG0RafhgmADiCw7ZideOnemjRU7TWvES7+jAbNpIM+mRG4Czxdh+qDCfui+5SjO608Pb/p8CIEbNqQyc4jR7vjHHxLU4uE4C/8D5OxtO95yPNbF1UkON2EXaV5YCMPCB93UdjOc+rptrqls4E1Mle6oVqPLOfPLz4/3b3xSXSyv1lv3rXN0ePcdpHAKKITUMXEYm++TjsubqcezGetKTfXO5IDb1+FmBAPiE4w02/DPncHYEoBJI6xR08RNsgL3f1Sv9ODBgn2Dg2WcI55lzFkzbz1FCzFkB/aLWUQTIJzdVCl5DoGM0+F7atXMqFWluT67P52kF3NFlg54ajKT2iGU9z1LfTF8QDGtb/vNqRZz9gAQeNH2vMh2d6IOCkTI0H/n90nwL1sQb/CPWXAQNBR35LtY2k6lti9OtodB7jDOGwL/I=
