language: node_js
node_js:
  - node
before_deploy: npm run package
deploy:
  provider: releases
  api_key:
    secure: KJf+zoveg2ZBNoW/Jd48rbIWhKM5GS8Ot8n2lXRdFwseCWVEuTroJE7YZb11E+Aw3kJqiZOi37IDIoZtHd31l2uJ0lJhCvnJDE4ky1mtcemeBUtOFUBafTqBV4eDHKPUVjNl0etO/d/8Qf84xksOJT1pSj9uyburh7ue5PXHY7mmktJ7JOVFYjgzTE1BipadLaErraVPkUSx6xceOwr/usFr83g1AsYr60QE/UIj3a7R7y3pzsSlmcrycAKjJ/qYC3aNjE8QiDhcN5UbEspmdFze6UUBbAMyRePQA/LaD8XXJM3bSqw57E7psXeiRivMocv0wFA9bagyR4l0kRt7QA9vuEUspbvWDV+TNgAMj6TqJ+ajtn0Mw4Ph1QbH+XuJWbDMPsq1q4OpsmABNgt+y2qwrhPJ0aB/V6CTGEvhw5xPRvvQhgXhWcp5BsDeIY+qLrZLgsxAZtGshyrqfEBl79FfOqEI6Z8Nc5ka1HvVQ1uFIoNE0XCIop3L2XtfvqTnIKKHQwDWn2Sqo5nkS4nQti0CniCVM1xeHcikSwm+Q3jIowoPBCkRkw5zIf2VvFKc6rx1hAhtcn3SBSAejs2d9SF4BXVNT47IqV5HoZmgOHEKjNxmo9XXIkwDgYPS7EBS5WFy1MRfituJTxGW1zKMOu8Wlrt7kybzW6yUUurhBzo=
  file: wukong-web.tgz
  on:
    repo: GyrosWorkshop/WukongWeb
    tags: true
