language: node_js
node_js:
- node
deploy:
  provider: s3
  on:
    repo: GyrosWorkshop/WukongWeb
    tags: true
  bucket: wukong-frontend
  region: ap-northeast-1
  local_dir: build
  detect_encoding: true
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAIHXJAIN2JAVUYVNA
  secret_access_key:
    secure: pWKGEouClvP2y67g0DJ8omZ9CP7zjjEQTMI3KM5UM8ZvrxmidGo1cr93yqTGQoYL0jiwSI0uULlCskR4MLQhwZ5dZTrske8c6jZYgqbh96l7KiiRS8EXCzloWLjxsBmENY7kpd2b9rxKBYsp1X+KJSTL2qJKki/gLR0tEziMbe6iDOpxYtxhf4/iYpc6djBdn13tpP4waDikAf5UJ+sQ4Wdvr2+d366z9TnyBFDfFGXa5a2eb4WF5cNJ8326OQCUWd7WTvcflGxv/S+Os88LI0hAnN95eWKfdxUWq2kj3E52qvPiR2QLjH6xk6qor6ZcoEQ8UbKJx/i089NYlodfCAkeRYCpGGJkUOy/t7hA7EXAllW0n0WST51SfkM+HhAhEdBdT/jB31dPW4INFuOfUmDuQPfCE7aqoQ6Xz0nwiKYU7qjFrUFdkUgrvmsKlgtPOgVXJlgYJvHGXuVc9ejKuWbBmj1ik2Rj+MR7dwVoA41djUavfKsyl3DXW6dU457aZ1VNr/h1TQ7ny7wo3cXMQ+HGWN5aFY9LOZikjYbx5pH84lJj6aXxqsAGGDwHf+QwEDlAUC7BHSMFL/HgVDya5eVZY+072vYxzkMtvkrrIVwRsaTbX+NGy3FhVbDgcw/CCXA6GiEsWDd6oQF/7mavsMqXZLcbkHuo7ITS/g1O+ck=
