dist: trusty
sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_script:
- npm install -g travis-ci-cloudfront-invalidation
deploy:
  provider: s3
  on:
    repo: GyrosWorkshop/WukongWeb
    tags: true
  bucket: wukong-frontend
  region: ap-northeast-1
  local_dir: build
  detect_encoding: true
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAIHXJAIN2JAVUYVNA
  secret_access_key:
    secure: pWKGEouClvP2y67g0DJ8omZ9CP7zjjEQTMI3KM5UM8ZvrxmidGo1cr93yqTGQoYL0jiwSI0uULlCskR4MLQhwZ5dZTrske8c6jZYgqbh96l7KiiRS8EXCzloWLjxsBmENY7kpd2b9rxKBYsp1X+KJSTL2qJKki/gLR0tEziMbe6iDOpxYtxhf4/iYpc6djBdn13tpP4waDikAf5UJ+sQ4Wdvr2+d366z9TnyBFDfFGXa5a2eb4WF5cNJ8326OQCUWd7WTvcflGxv/S+Os88LI0hAnN95eWKfdxUWq2kj3E52qvPiR2QLjH6xk6qor6ZcoEQ8UbKJx/i089NYlodfCAkeRYCpGGJkUOy/t7hA7EXAllW0n0WST51SfkM+HhAhEdBdT/jB31dPW4INFuOfUmDuQPfCE7aqoQ6Xz0nwiKYU7qjFrUFdkUgrvmsKlgtPOgVXJlgYJvHGXuVc9ejKuWbBmj1ik2Rj+MR7dwVoA41djUavfKsyl3DXW6dU457aZ1VNr/h1TQ7ny7wo3cXMQ+HGWN5aFY9LOZikjYbx5pH84lJj6aXxqsAGGDwHf+QwEDlAUC7BHSMFL/HgVDya5eVZY+072vYxzkMtvkrrIVwRsaTbX+NGy3FhVbDgcw/CCXA6GiEsWDd6oQF/7mavsMqXZLcbkHuo7ITS/g1O+ck=
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWSAccessKey -s $AWSSecretKey -c $CloudFrontDistributionId -i '/sw.js,/index.html' -b 'master' -p 'false'
env:
  global:
  - secure: SnScDwiyx7EQoSWETXFrWYrPpSlC3H/PgR3j8/TBpiNFDfGmHRff9IAeB58PimWhnx5jSh4BYZyQ4FAGt2xzT7fzVtQc/Gcc9evl+tVylpM3WGWvgotSAoPiAypxfZst98NkDlbO9X4L1+1WhxGSiJk0e0B7J0L6M7Xg3Q8loYpCnnRoRd1sy/Okaq/Z5VdAvXSpU1EW1G1Wl2ZnGILTKU8p4i1BemED8Gv/9hLsn5VtLD76bLH8uXdAlX1G9aaYd8Sjq3U+aoBMe8C9WjlMz//zbHm9+XOeFQe49aRtbqYwRv+XHTjbiJ+NjCyy/KQMo5qgGZQueUtPnmyDgtHeH03TWayYyHT8umv2svdwiL0UsV6mZpDtfZbTPVAke/E2Us0ElyrNPpUwIsjelq7fw8WftBfips6eGA4UroNRsSIutYc9U8f1mE3fSXYboFZZhpNvpTeh8IjKfNXZ1nQ/trKqZw3qxz1Ngv2ekWpdXEXcz74SMjNr0zZSygOl97BC5K17dsM/8YUhOzGGN334/GDmroNhdwn+Xo488Ll9/C+ajE/HEqYg0yMRK2Bhrai5gad1umS1wyhOz8yUPzQ++V+4KHEU0nFALnnlehhMDwiY6oqEBUnc6+OHmj4+u1LO7iR5x16YAcIKg+I0QtivZD6V2Y3buwMw14OPcxw8A3I=
  - secure: Te9kB0UZf9hbGf1O0FUokAGTlJ65Oy4DKQwZtE+U/mj2qjRoh++dJiw80+iDBMdNf5IAgAKHGF8Fj+/YfmZs39QTyu5uPf2u4izo5j/Q/l8uUYAfbjJN+k3FSqThYdh4CjG4cu9qFn28vOL7gKGY32dl9ZL235mvDg9WUxIp1c5YfKixageQMkjNuqpXtufYMhH1xhTM4UjOZr0qoZ1mGske6eZaDDbhVkwvPQHrOY3JhQB0adXPB3lFhwc2W2V3svV9qGCtoEdvWj7HkOMdTFvYTSIwpK/Nv5Q6FC3hmG5e+U773KA5TtUGVIG25cH5NdYx9fPym5tZjcLM7uZ7yjuseoR/wyva0aXNV5JvAqPvLuB6Gc+s9DFTMBVFjk2qYLt4w7KEU1LvGYHUJoCdp+F83dChtB77E7FdW8IT3I6461QCA+kLYQMvbjEURuu8GtxkLt4ZV+q7VmzLRocwBRaldjw7X/vVDuhOKiEDO57BgugFuqEvrTUalePyJBhDOTdvAtqvOZEQcnUozm94fJJOuLyxDAHC8ATI3AdNv/SbzlNAHTs3flTnITyx5aSGmw6IXsgJqrIBmpsXgjlIImxLw/ZDkHEOKUBivx1RIFKXLeWmWXmc/hS2KA/faGgrEQ37ajkeqRWf8UdxiifS7n70Ud+MWCy8+GrdcKj+tCI=
  - secure: N4kBT4gF2iKqo/HJT09lDID2xifaG3Ut+ZtRjHaUBKkcH7paNKMFnDks5ZCd01bCxznV6hpUb8wyx6ygsxmoOFVmN0Zy9L3suVhsRRa8csclVF21IzAqiJ9DsPXYgO5JKuix3jRsJ4/WXk0xC+y39lNVKOPLD+3d1JCCS7G2B8pSXhJ5ggaeaQLkN2mgcqPVmBNlZ/6qoF2mlNfZge5tF9D/FDFYUgNcSwQsPDtC3n7axrjARlViWfcu5cVW6BuJdY0loafO/DuVzw0DkSTuqYgnvzAHbTb+fPCOvLYteRsec7+TmMK2/LIzUbrWl8dLUOAxQxc3pT78gT81k/GycffzOleDUaiyXTakxJEOjP3m7oyB/DDNJ6pMcFtzL3TTX1XLpewg4zrCCXLkJlzCV/B9N9YylNdd1v3hAsxWOVQSoSjkBIZpUVrktog743gXyCD6D5FYeIyzLXIOmITHrSm1li/Q1yTjdb2JTq1bEtQM5ZsKoQuqDiCLR9cQlsZoNurj6EFNiNu0LuYjPQUUllmvAx8TBUJjVTsCYAVlPzGlXsqYkniBWUmxgX2FUlYXUlEdA2wlAiDN3aMUnYIfn7W3FdMq8PLMQdYDRFRryBrJdqfTZLIc2Y11DoKG0ImlGHPgYlxVCln+h4Ibt1f6eMMIkvfg4K5qNqWNo/iGbJc=
